export enum SettingsActionType {
    SET,
    UPDATE,
    SET_THEME,
    ADD_CONFIGURATION,
    UPDATE_CONFIGURATION,
    DELETE_CONFIGURATIONS,
    SET_SELECTED_CONFIGURAION,
    UPDATE_ADVANCE_CONFIGURATION,
}
