name: BuildAll

on: workflow_dispatch

#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main

#on:
#  push:
#    tags:
#      - '*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
        architecture: 'x64'
    - uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
    - uses: actions/checkout@v2
    
    - name: Get version
      uses: KageKirin/get-node-package-version@v0
      id: package_version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
        cache: 'yarn'
        
    - run: yarn
    - run: node update_version.js
    
    - name: Build XMRig, libUV, OpenSSL & hwloc
      run: cd xmrig/lib-builder && mkdir build && mkdir build/src && mkdir build/build && make all && cd .. && cd .. 
        
    - run: yarn
    - run: cd android && ./gradlew bundleRelease && cd ..
    
    - name: install bundletool
      uses: enniel/bundletool-runner@v1.1.0
    
    - run: java -jar /home/runner/bundletool/bundletool.jar build-apks --mode=universal --bundle=./android/app/build/outputs/bundle/release/app-release.aab --output=./android/app/build/outputs/bundle/release/app-release.apks
    - run: mv ./android/app/build/outputs/bundle/release/app-release.apks ./android/app/build/outputs/bundle/release/app-release-apk.zip
    - run: unzip ./android/app/build/outputs/bundle/release/app-release-apk.zip
    - run: mv universal.apk ./android/app/build/outputs/bundle/release/app-release.apk
    - run: rm ./android/app/build/outputs/bundle/release/app-release-apk.zip
    - run: mv ./android/app/build/outputs/bundle/release/app-release.apk ./android/app/build/outputs/bundle/release/xmrig-for-android_v${{ steps.bump_version.outputs.new_tag }}.apk
    - run: mv ./android/app/build/outputs/bundle/release/app-release.aab ./android/app/build/outputs/bundle/release/xmrig-for-android_v${{ steps.bump_version.outputs.new_tag }}.aab
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./android/app/build/outputs/bundle/release
        
    #- name: Install hub
    #  uses: geertvdc/setup-hub@master
    #  env:
    #    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    #- name: run hub commands
    #  env:
    #    GITHUB_USER: ${{ secrets.USER }}
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run: |
    #       hub release edit -dp -a ./android/app/build/outputs/bundle/release/xmrig-for-android_v${GITHUB_REF##*/}-signed.apk -a ./android/app/build/outputs/bundle/release/xmrig-for-android_v${GITHUB_REF##*/}.apk -a ./android/app/build/outputs/bundle/release/xmrig-for-android_v${GITHUB_REF##*/}.aab -m "${GITHUB_REF##*/}" ${GITHUB_REF##*/}
      
      
